/* © 2026 Al.G.B.r. Digital Studio. Proprietary source code. All rights reserved. */
(()=>{
 const form=document.getElementById('wizard'); if(!form) return;
 const steps=[...document.querySelectorAll('.wizard-step')],progress=document.getElementById('progress'),next=document.getElementById('next'),prev=document.getElementById('prev');let idx=0;
 const lang=(document.documentElement.lang||'de').slice(0,2);
 const T={
  de:{next:'Weiter',summary:'Zusammenfassung erstellen',copied:'Kopiert ✓',file:'algbr-projektanfrage.txt',subject:'Projektanfrage',title:'PROJEKTANFRAGE — Al.G.B.r.',labels:['Projektart','Branche','Ziel','Funktionen','Marke / Logo','Texte / Bilder','Beispiele / Links','Budget','Zeitrahmen','Name / Firma','E-Mail','Weitere Hinweise'],none:'noch offen',dash:'—'},
  en:{next:'Next',summary:'Create summary',copied:'Copied ✓',file:'algbr-project-enquiry.txt',subject:'Project enquiry',title:'PROJECT ENQUIRY — Al.G.B.r.',labels:['Project type','Industry','Goal','Functions','Brand / logo','Texts / images','Examples / links','Budget','Timeline','Name / company','Email','Additional notes'],none:'not decided yet',dash:'—'},
  fr:{next:'Suivant',summary:'Créer le résumé',copied:'Copié ✓',file:'demande-projet-algbr.txt',subject:'Demande de projet',title:'DEMANDE DE PROJET — Al.G.B.r.',labels:['Type de projet','Secteur','Objectif','Fonctions','Marque / logo','Textes / images','Exemples / liens','Budget','Délai','Nom / entreprise','E-mail','Informations complémentaires'],none:'à définir',dash:'—'}
 }[lang]||null;
 const tr=T||{next:'Weiter',summary:'Zusammenfassung erstellen',copied:'Kopiert ✓',file:'algbr-projektanfrage.txt',subject:'Projektanfrage',title:'PROJEKTANFRAGE — Al.G.B.r.',labels:['Projektart','Branche','Ziel','Funktionen','Marke / Logo','Texte / Bilder','Beispiele / Links','Budget','Zeitrahmen','Name / Firma','E-Mail','Weitere Hinweise'],none:'noch offen',dash:'—'};
 const params=new URLSearchParams(location.search);
 if(params.get('type')){const map={de:{landing:'Landingpage',website:'Professionelle Website',shop:'Webshop',app:'Web-App / PWA',crm:'CRM / Booking / Cloud'},en:{landing:'Landing page',website:'Business website',shop:'Online store',app:'Web app / PWA',crm:'CRM / Booking / Cloud'},fr:{landing:'Landing page',website:'Site professionnel',shop:'Boutique en ligne',app:'Application web / PWA',crm:'CRM / Réservation / Cloud'}};document.getElementById('type').value=(map[lang]||map.de)[params.get('type')]||params.get('type')}
 if(params.get('industry')) document.getElementById('industry').value=params.get('industry');
 if(params.get('preset')==='beauty'){document.getElementById('industry').value='beauty'; const vals={de:'CRM / Booking / Cloud',en:'CRM / Booking / Cloud',fr:'CRM / Réservation / Cloud'};document.getElementById('type').value=vals[lang]||vals.de;}
 function show(){steps.forEach((s,i)=>s.classList.toggle('active',i===idx));progress.style.width=((idx+1)/steps.length*100)+'%';prev.hidden=idx===0;next.hidden=idx===steps.length-1;next.textContent=idx===steps.length-2?tr.summary:tr.next;if(idx===steps.length-1) build();window.scrollTo({top:0,behavior:'smooth'})}
 function valid(){return [...steps[idx].querySelectorAll('[required]')].every(el=>{if(!el.value.trim()){el.focus();return false}return true})}
 next.addEventListener('click',()=>{if(!valid())return;idx=Math.min(idx+1,steps.length-1);show()});prev.addEventListener('click',()=>{idx=Math.max(0,idx-1);show()});
 function build(){const fd=new FormData(form),features=fd.getAll('features'),L=tr.labels;const txt=`${tr.title}\n\n${L[0]}: ${fd.get('type')}\n${L[1]}: ${fd.get('industry')}\n${L[2]}: ${fd.get('goal')}\n\n${L[3]}:\n${features.map(x=>'• '+x).join('\n')||'• '+tr.none}\n\n${L[4]}: ${fd.get('brand')}\n${L[5]}: ${fd.get('content')}\n${L[6]}: ${fd.get('links')||tr.dash}\n\n${L[7]}: ${fd.get('budget')}\n${L[8]}: ${fd.get('timeline')}\n${L[9]}: ${fd.get('name')}\n${L[10]}: ${fd.get('email')}\n${L[11]}: ${fd.get('notes')||tr.dash}`;document.getElementById('summary').textContent=txt;document.getElementById('mail').href='mailto:algbr@gmail.com?subject='+encodeURIComponent(tr.subject+' — '+fd.get('type'))+'&body='+encodeURIComponent(txt);window.__summary=txt;}
 document.getElementById('copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(window.__summary||'');document.getElementById('copy').textContent=tr.copied});document.getElementById('download').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([window.__summary||''],{type:'text/plain'}));a.download=tr.file;a.click();URL.revokeObjectURL(a.href)});
 show();
})();